import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from 'components/header'
import { getSession } from 'next-auth/react';
import SignIn from 'components/SignIn'
import SideBar from 'components/SideBar'
import FeedComponent from 'components/FeedComponent'
import RightSide from 'components/RightSide';

const inter = Inter({ subsets: ['latin'] })

export default function Home({session}) {
 // console.log(session)
  if(!session) return <SignIn/>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className = 'flex  justify-between h-screen bg-gray-100' >
        <SideBar/>
        <FeedComponent/>
        <RightSide/> 
      </main>
    </>
  )
}

export  async function getServerSideProps(context) {
  //console.log(context)
  const session = await getSession(context)
  console.log(session)
  let res = session ? session.user : null
  return{props:{session:res}
  }
}
